name-template: 'Latest Release'
tag-template: 'Latest Release'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'add'
      - 'new'
  - title: 'Fixes'
    labels:
      - 'fix'
  - title: 'Workspace'
    labels:
      - 'update'
      - 'environment'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
template: |
  ## ChangeLog
    $CHANGES
  ## Contributors
  $CONTRIBUTORS