name: Document deploy
on:
  push:
    branches: [ master ]
  release:
    branches: [ master ]
    types: [ created, released, prereleased, published, edited ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          cache: gradle

      - run: chmod 777 ./gradlew

      - name: Build documents
        run: ./gradlew dokkaHtml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dokka